### ISSUE TITLE
Install error on MacOS

### ISSUE THREAD

**Issue by woensug-choi** [jbnunn/ROSGazeboDesktop#1]
During installation I got error ending with followings, any solutions?

Step 8/27 : RUN apt-get install -y ros-melodic-desktop-full
 ---> Using cache
 ---> 55a4ec0a9102
Step 9/27 : RUN rosdep init && rosdep update
 ---> Running in e002862aacaa
/bin/sh: 1: rosdep: not found
The command '/bin/sh -c rosdep init && rosdep update' returned a non-zero code: 127

**Comment by woensug-choi** [comment]
Solved by adding a line to install python-rosdep in Dockerfile

**Comment by samlaf** [comment]
I had the same error. Fixed by adding
RUN apt install python-rosdep
before rosdep init

**Comment by AbdelMounhim** [comment]
need to install python-rosdep + python 3.7  + pip  (python3-pip instead of python-pip) 

RUN apt-get install -y ros-melodic-desktop-full **python3.7 python-rosdep**
RUN apt-get install -y git wget curl nano mercurial **python3-pip**
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.7 get-pip.py
RUN rm get-pip.py
